import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Flutter App',
        home: HomeScreen(),
        theme: ThemeData());
  }
}

// ignore: must_be_immutable
class HomeScreen extends StatelessWidget {
  var whatsapp = [
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
    {
      "Name": "Resourses",
      "Chat": "You: Photo",
      "Image": "assets/images/i1.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Deepanshu Methi",
      "Chat": "Photo",
      "Image": "assets/images/i2.jpg",
      "Time": "2:25 am",
    },
    {
      "Name": "WSLC-147 Flutter Development",
      "Cumber": "~ Wscubetech: Hello Everyone",
      "Image": "assets/images/i3.jpeg",
      "Time": "3:15 am",
    },
    {
      "Name": "Alwar family",
      "Chat": "Mona Dii: ha ha ha ha",
      "Image": "assets/images/i4.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "WSLC STUDENT GROUP",
      "Chat": "~ Anjali: sent",
      "Image": "assets/images/i5.jpeg",
      "Time": "9:38 pm",
    },
    {
      "Name": "Dhurv",
      "Chat": "Ok",
      "Image": "assets/images/i6.jpg",
      "Time": "10:25 pm",
    },
    {
      "Name": "InventEdu",
      "Chat": "Shivam Degi Tariner: https/gjbnbbbnlb",
      "Image": "assets/images/i7.jpg",
      "Time": "Yesterday",
    },
    {
      "Name": "Hardik Saini",
      "Chat": "Yes bro",
      "Image": "assets/images/i8.jpeg",
      "Time": "03/08/23",
    },
    {
      "Name": "Unofficial A1",
      "Chat": "Harsh: Hn",
      "Image": "assets/images/i8.webp",
      "Time": "02/08/23",
    },
    {
      "Name": "Gagan Saini",
      "Chat": "Accha",
      "Image": "assets/images/i9.webp",
      "Time": "5:25 am",
    },
    {
      "Name": "Mohit Singh",
      "Chat": "Photo",
      "Image": "assets/images/i10.jpeg",
      "Time": "01/08/23",
    },
    {
      "Name": "Anshu Vasist",
      "Chat": "You reacted to sahi ha yrr to website ",
      "Image": "assets/images/i11.jpeg",
      "Time": "7:25 pm",
    },
    {
      "Name": "Bhavika Mitrc",
      "Chat": "Reacted to mast aak daam",
      "Image": "assets/images/i12.jpeg",
      "Time": "31/07/23",
    },
    {
      "Name": "Hemant Bhai",
      "Chat": "Raected ha ha ha haa",
      "Image": "assets/images/i13.jpg",
      "Time": "31/07/23",
    },
    {
      "Name": "Kunal Saini",
      "Chat": "Photo",
      "Image": "assets/images/i14.jpeg",
      "Time": "28/07/23",
    },
    {
      "Name": "Chanchal Bhabhi",
      "Chat": "Hllo Bhabhi ji",
      "Image": "assets/images/i15.webp",
      "Time": "23/07/23",
    },
  ];

  HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // appBar: AppBar(
      //     // title: Text("Whatsapp"),
      //     // backgroundColor: const Color.fromARGB(255, 1, 9, 15),
      //     // centerTitle: true,
      //     ),
      backgroundColor: Color.fromARGB(255, 239, 253, 253),
      body: Container(
        child: Stack(
          children: [
            Container(
              height: 160,
              width: double.infinity,
              color: Color.fromARGB(255, 32, 50, 61),
            ),
            Row(
              children: [
                Padding(padding: EdgeInsets.only(left: 20, top: 120)),
                Container(
                  height: 60,
                  width: 130,
                  // color: Colors.amber,
                  child: Image.asset(
                    "assets/images/Whatsapp logo.png",
                  ),
                ),
                Padding(padding: EdgeInsets.only(left: 110)),
                Container(
                    height: 28,
                    width: 28,
                    child: Image.asset("assets/images/camera.png")),
                Padding(padding: EdgeInsets.only(left: 30)),
                Container(
                  height: 30,
                  width: 30,
                  child: Icon(
                    FontAwesomeIcons.search,
                    color: const Color.fromARGB(113, 255, 255, 255),
                    size: 25,
                  ),
                ),
                Padding(padding: EdgeInsets.only(left: 25)),
                Container(
                    height: 20,
                    width: 20,
                    child: Image.asset("assets/images/dots.png")),
              ],
            ),
            Row(
              children: [
                Padding(padding: EdgeInsets.only(top: 250, left: 20)),
                Container(
                  // color: Colors.amber,
                  child: Icon(
                    FontAwesomeIcons.peopleGroup,
                    color: const Color.fromARGB(113, 255, 255, 255),
                  ),
                ),
                Padding(padding: EdgeInsets.only(left: 50)),
                Container(
                  // color: Colors.amber,
                  child: Text(
                    "Chats",
                    style: TextStyle(
                        color: Color.fromARGB(255, 30, 186, 147),
                        fontSize: 20,
                        fontWeight: FontWeight.w500),
                  ),
                ),
                Padding(padding: EdgeInsets.only(left: 60)),
                Container(
                  // color: Colors.amber,
                  child: Text(
                    "Status",
                    style: TextStyle(
                        color: const Color.fromARGB(149, 255, 255, 255),
                        fontSize: 20,
                        fontWeight: FontWeight.w500),
                  ),
                ),
                Padding(padding: EdgeInsets.only(left: 70)),
                Container(
                  // color: Colors.amber,
                  child: Text(
                    "Calls",
                    style: TextStyle(
                        color: const Color.fromARGB(142, 255, 255, 255),
                        fontSize: 20,
                        fontWeight: FontWeight.w500),
                  ),
                ),
              ],
            ),
            Column(
              children: [
                Padding(padding: const EdgeInsets.only(top: 155, left: 240)),
                Container(
                  height: 5,
                  width: 120,
                  color: const Color.fromARGB(255, 30, 186, 147),
                )
              ],
            ),
            SingleChildScrollView(
              child: Column(
                children: [
                  Padding(padding: EdgeInsets.only(top: 160)),
                  Container(
                      height: 1000,
                      width: double.infinity,
                      color: Color.fromARGB(255, 255, 255, 255),
                      child: ListView.builder(
                          itemBuilder: (context, index) {
                            return ListTile(
                              leading: CircleAvatar(
                                backgroundImage:
                                    AssetImage("${whatsapp[index]["Image"]}"),
                              ),
                              title: Text("${whatsapp[index]["Name"]}"),
                              subtitle: Text("${whatsapp[index]["Chat"]}"),
                              trailing: Text("${whatsapp[index]["Time"]}"),
                            );
                          },
                          itemCount: whatsapp.length)),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
